#!/bin/sh

action="$1"
if [ "$1" = "configure" ] && [ -z "$2" ]; then
  action="install"
elif [ "$1" = "configure" ] && [ -n "$2" ]; then
  action="upgrade"
fi

case "$action" in
  "1" | "install")
    ;;
  "2" | "upgrade")
    ;;
  *)
    /opt/agent-server/bin/agent-server -action uninstall
    ;;
esac