// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://www.jkstack.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "获取节点列表",
                "operationId": "/api/agents",
                "parameters": [
                    {
                        "enum": [
                            "example-agent",
                            "container-agent",
                            "metrics-agent",
                            "..."
                        ],
                        "type": "string",
                        "description": "节点类型,不指定则列出所有类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "分页编号",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "minimum": 10,
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/agents.info"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/agents/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "获取某个节点信息",
                "operationId": "/api/agents/info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/agents.info"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/foo/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foo"
                ],
                "summary": "调用example类型的agent",
                "operationId": "/api/foo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Success"
                        }
                    }
                }
            }
        },
        "/info/server": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "获取当前服务器状态",
                "operationId": "/api/info/server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "payload": {
                                            "$ref": "#/definitions/info.serverInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agents.info": {
            "type": "object",
            "properties": {
                "arch": {
                    "description": "操作系统位数",
                    "type": "string",
                    "enum": [
                        "i386",
                        "x86_64",
                        "..."
                    ],
                    "example": "x86_64"
                },
                "id": {
                    "description": "agent-id",
                    "type": "string",
                    "example": "ct-01"
                },
                "ip": {
                    "description": "ip地址",
                    "type": "string",
                    "example": "127.0.0.1"
                },
                "mac": {
                    "description": "mac地址",
                    "type": "string",
                    "example": "00:15:5d:c9:e0:17"
                },
                "os": {
                    "description": "操作系统类型",
                    "type": "string",
                    "enum": [
                        "windows",
                        "linux"
                    ],
                    "example": "linux"
                },
                "platform": {
                    "description": "操作系统名称",
                    "type": "string",
                    "enum": [
                        "debian",
                        "centos",
                        "..."
                    ],
                    "example": "debian"
                },
                "type": {
                    "description": "agent类型",
                    "type": "string",
                    "example": "container-agent"
                },
                "version": {
                    "description": "agent版本号",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.Success": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "payload": {}
            }
        },
        "info.serverInfo": {
            "type": "object",
            "properties": {
                "agents": {
                    "description": "当前连接的agent数量",
                    "type": "integer",
                    "example": 10
                },
                "is_blocking": {
                    "description": "是否处于限流状态",
                    "type": "boolean",
                    "example": false
                },
                "version": {
                    "description": "服务端版本号",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "TODO",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "agent-server",
	Description:      "jkagent management server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
