basePath: /api
definitions:
  agents.info:
    properties:
      arch:
        description: 操作系统位数
        enum:
        - i386
        - x86_64
        - '...'
        example: x86_64
        type: string
      id:
        description: agent-id
        example: ct-01
        type: string
      ip:
        description: ip地址
        example: 127.0.0.1
        type: string
      mac:
        description: mac地址
        example: 00:15:5d:c9:e0:17
        type: string
      os:
        description: 操作系统类型
        enum:
        - windows
        - linux
        example: linux
        type: string
      platform:
        description: 操作系统名称
        enum:
        - debian
        - centos
        - '...'
        example: debian
        type: string
      type:
        description: agent类型
        example: container-agent
        type: string
      version:
        description: agent版本号
        example: 1.0.0
        type: string
    type: object
  api.Success:
    properties:
      code:
        example: 0
        type: integer
      payload: {}
    type: object
  info.serverInfo:
    properties:
      agents:
        description: 当前连接的agent数量
        example: 10
        type: integer
      is_blocking:
        description: 是否处于限流状态
        example: false
        type: boolean
      version:
        description: 服务端版本号
        example: 1.0.0
        type: string
    type: object
  metrics.connection:
    type: object
  metrics.core:
    properties:
      core:
        description: 所在物理核上的编号
        example: 0
        type: integer
      cores:
        description: 某块CPU上的编号
        example: 0
        type: integer
      mhz:
        description: 核心频率
        example: 1600
        type: number
      model:
        description: CPU型号
        example: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
        type: string
      physical:
        description: 物理CPU编号
        example: 0
        type: integer
      processor:
        description: 第几个核心
        example: 0
        type: integer
    type: object
  metrics.disk:
    properties:
      disks:
        description: 逻辑分区
        example:
        - /boot
        - /home
        items:
          type: string
        type: array
      model:
        description: 品牌型号
        example: Samsung SSD 870 QVO 1TB
        type: string
      total:
        description: 容量
        example: 1000204886016
        type: integer
      type:
        description: 磁盘类型
        enum:
        - HDD
        - SSD
        example: HDD
        type: string
    type: object
  metrics.dynamicInfo:
    properties:
      connections:
        description: 连接列表
        items:
          $ref: '#/definitions/metrics.connection'
        type: array
      process:
        description: 进程列表
        items:
          $ref: '#/definitions/metrics.process'
        type: array
      usage:
        $ref: '#/definitions/metrics.usage'
        description: usage数据
    type: object
  metrics.interfaceUsage:
    properties:
      bytes_recv:
        description: 接收字节数
        example: 24422
        type: integer
      bytes_sent:
        description: 发送字节数
        example: 6162729
        type: integer
      name:
        description: 网卡名称
        example: eth0
        type: string
      packets_recv:
        description: 接收数据包数量
        example: 4399
        type: integer
      packets_sent:
        description: 发送数据包数量
        example: 5699
        type: integer
    type: object
  metrics.intf:
    properties:
      addrs:
        description: 网卡上绑定的IP地址列表
        example:
        - 192.168.1.100
        items:
          type: string
        type: array
      flags:
        description: 网卡附加参数
        example:
        - UP
        - BROADCAST
        - RUNNING
        - MULTICAST
        items:
          type: string
        type: array
      index:
        description: 网卡下标
        example: 0
        type: integer
      mac:
        description: 网卡mac地址
        example: 26:29:93:f2:84:22
        type: string
      mtu:
        description: 网卡mtu
        example: 1500
        type: integer
      name:
        description: 网卡名称
        example: lo
        type: string
    type: object
  metrics.partition:
    properties:
      fstype:
        description: 文件系统类型
        example: NTFS
        type: string
      inodes:
        description: inode数量
        example: 4072701
        type: integer
      mount:
        description: 'linux为挂载路径如/run，windows为盘符如C:'
        example: /boot
        type: string
      opts:
        description: 附加信息
        example:
        - rw
        - nosuid
        - nodev
        items:
          type: string
        type: array
      total:
        description: 总容量
        example: 209666048
        type: integer
    type: object
  metrics.partitionUsage:
    properties:
      free:
        description: 剩余字节数
        example: 232815064
        type: integer
      inode_free:
        description: inode剩余数量
        example: 15998934
        type: integer
      inode_usage:
        description: inode使用率
        example: 5.64
        type: number
      inode_used:
        description: inode已使用数量
        example: 778282
        type: integer
      name:
        description: 'linux为挂载路径如/run，windows为盘符如C:'
        example: /
        type: string
      usage:
        description: 磁盘使用率
        example: 6.27
        type: number
      used:
        description: 已使用字节数
        example: 16920992
        type: integer
    type: object
  metrics.process:
    type: object
  metrics.staticInfo:
    properties:
      cpu:
        properties:
          cores:
            description: 每个核心参数
            items:
              $ref: '#/definitions/metrics.core'
            type: array
          logical:
            description: 逻辑核心数
            example: 4
            type: integer
          physical:
            description: 物理核心数
            example: 2
            type: integer
        type: object
      disks:
        description: 物理磁盘列表
        items:
          $ref: '#/definitions/metrics.disk'
        type: array
      gateway:
        description: 网关地址
        example: 192.168.1.1
        type: string
      host:
        properties:
          name:
            description: 主机名
            example: DESKTOP-OQ8O3DR
            type: string
          uptime:
            description: 启动时长
            example: 1900
            type: integer
        type: object
      interface:
        description: 网卡列表
        items:
          $ref: '#/definitions/metrics.intf'
        type: array
      kernel:
        properties:
          arch:
            description: 位数
            enum:
            - x86_64
            - i386
            - '...'
            example: x86_64
            type: string
          version:
            description: 内核版本
            example: 3.10.0-1062.el7.x86_64
            type: string
        type: object
      memory:
        properties:
          physical:
            description: 物理内存大小
            example: 33363566592
            type: integer
          swap:
            description: swap内存大小
            example: 8589930496
            type: integer
        type: object
      os:
        properties:
          install:
            description: 系统安装时间
            example: 1661396019
            type: integer
          name:
            description: 系统类型
            enum:
            - linux
            - windows
            example: linux
            type: string
          platform_name:
            description: 系统名称
            enum:
            - redhat
            - centos
            - debian
            - ubuntu
            - '...'
            example: centos
            type: string
          platform_version:
            description: 系统版本号
            example: 7.7.1908
            type: string
          startup:
            description: 系统启动时间
            example: 1661396019
            type: integer
        type: object
      partitions:
        description: 逻辑分区列表
        items:
          $ref: '#/definitions/metrics.partition'
        type: array
      time:
        description: 客户端时间
        example: 1661396019
        type: integer
      user:
        description: 用户列表
        items:
          $ref: '#/definitions/metrics.user'
        type: array
    type: object
  metrics.usage:
    properties:
      cpu:
        properties:
          usage:
            description: CPU使用率(百分比)
            example: 2.3
            type: number
        type: object
      interface:
        description: 网卡
        items:
          $ref: '#/definitions/metrics.interfaceUsage'
        type: array
      memory:
        properties:
          available:
            description: 可用字节数
            example: 201332
            type: integer
          free:
            description: 剩余字节数
            example: 94896
            type: integer
          swap_free:
            description: swap剩余字节数
            example: 7242344
            type: integer
          swap_total:
            description: swap总字节数
            example: 8388608
            type: integer
          swap_used:
            description: swap已使用字节数
            example: 1146264
            type: integer
          total:
            description: 总字节数
            example: 1956784
            type: integer
          usage:
            description: 内存使用率(百分比)
            example: 1.2
            type: number
          used:
            description: 已使用字节数
            example: 1595712
            type: integer
        type: object
      partitions:
        description: 分区
        items:
          $ref: '#/definitions/metrics.partitionUsage'
        type: array
    type: object
  metrics.user:
    properties:
      gid:
        description: 用户组ID
        example: "0"
        type: string
      id:
        description: 用户ID
        example: "0"
        type: string
      name:
        description: 用户名
        example: root
        type: string
    type: object
info:
  contact:
    url: https://www.jkstack.com
  description: jkagent management server.
  title: agent-server
  version: TODO
paths:
  /agents:
    get:
      operationId: /api/agents
      parameters:
      - description: 节点类型,不指定则列出所有类型
        enum:
        - example-agent
        - container-agent
        - metrics-agent
        - '...'
        in: query
        name: type
        type: string
      - default: 1
        description: 分页编号
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        minimum: 10
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/agents.info'
                  type: array
              type: object
      summary: 获取节点列表
      tags:
      - agents
  /agents/{id}:
    get:
      operationId: /api/agents/info
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/agents.info'
              type: object
      summary: 获取某个节点信息
      tags:
      - agents
  /foo/{id}:
    get:
      operationId: /api/foo
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Success'
      summary: 调用example类型的agent
      tags:
      - foo
  /info/server:
    get:
      operationId: /api/info/server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/info.serverInfo'
              type: object
      summary: 获取当前服务器状态
      tags:
      - info
  /metrics/{id}/dynamic:
    get:
      operationId: /api/metrics/dynamic
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/metrics.dynamicInfo'
              type: object
      summary: 获取节点的所有动态数据
      tags:
      - metrics
  /metrics/{id}/dynamic/connections:
    get:
      operationId: /api/metrics/dynamic/connections
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/metrics.connection'
                  type: array
              type: object
      summary: 获取节点的连接列表数据
      tags:
      - metrics
  /metrics/{id}/dynamic/process:
    get:
      operationId: /api/metrics/dynamic/process
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/metrics.process'
                  type: array
              type: object
      summary: 获取节点的所有进程列表数据
      tags:
      - metrics
  /metrics/{id}/dynamic/usage:
    get:
      operationId: /api/metrics/dynamic/usage
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/metrics.usage'
              type: object
      summary: 获取节点的usage动态数据
      tags:
      - metrics
  /metrics/{id}/static:
    get:
      operationId: /api/metrics/static
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/metrics.staticInfo'
              type: object
      summary: 获取节点的静态数据
      tags:
      - metrics
swagger: "2.0"
