basePath: /api
definitions:
  agents.info:
    properties:
      arch:
        enum:
        - i386
        - x86_64
        - '...'
        example: 操作系统位数
        type: string
      id:
        example: agent_id
        type: string
      ip:
        example: ip地址
        type: string
      mac:
        example: mac地址
        type: string
      os:
        enum:
        - windows
        - linux
        example: 操作系统类型
        type: string
      platform:
        enum:
        - debian
        - centos
        - '...'
        example: 操作系统名称
        type: string
      type:
        example: agent类型
        type: string
      version:
        example: agent版本号
        type: string
    type: object
  api.Success:
    properties:
      code:
        example: 0
        type: integer
      payload: {}
      reqid:
        example: 20220812-00000001-2bf6c4
        type: string
    type: object
info:
  contact:
    url: https://www.jkstack.com
  description: jkagent management server.
  title: agent-server
paths:
  /agents:
    get:
      description: 获取节点列表
      operationId: /api/agents
      parameters:
      - description: 节点类型,不指定则列出所有类型
        in: query
        name: type
        type: string
      - default: 1
        description: 分页编号
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        minimum: 10
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/agents.info'
                  type: array
              type: object
      tags:
      - agents
  /agents/{id}:
    get:
      description: 获取某个节点信息
      operationId: /api/agents/info
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/agents.info'
              type: object
      tags:
      - agents
  /foo/{id}:
    get:
      description: 调用example类型的agent
      operationId: /api/foo
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Success'
      tags:
      - foo
swagger: "2.0"
