basePath: /api
definitions:
  agents.info:
    properties:
      arch:
        description: 操作系统位数
        enum:
        - i386
        - x86_64
        - '...'
        example: x86_64
        type: string
      id:
        description: agent-id
        example: ct-01
        type: string
      ip:
        description: ip地址
        example: 127.0.0.1
        type: string
      mac:
        description: mac地址
        example: 00:15:5d:c9:e0:17
        type: string
      os:
        description: 操作系统类型
        enum:
        - windows
        - linux
        example: linux
        type: string
      platform:
        description: 操作系统名称
        enum:
        - debian
        - centos
        - '...'
        example: debian
        type: string
      type:
        description: agent类型
        example: container-agent
        type: string
      version:
        description: agent版本号
        example: 1.0.0
        type: string
    type: object
  api.Success:
    properties:
      code:
        example: 0
        type: integer
      payload: {}
    type: object
  info.serverInfo:
    properties:
      agents:
        description: 当前连接的agent数量
        example: 10
        type: integer
      is_blocking:
        description: 是否处于限流状态
        example: false
        type: boolean
      version:
        description: 服务端版本号
        example: 1.0.0
        type: string
    type: object
info:
  contact:
    url: https://www.jkstack.com
  description: jkagent management server.
  title: agent-server
  version: TODO
paths:
  /agents:
    get:
      operationId: /api/agents
      parameters:
      - description: 节点类型,不指定则列出所有类型
        enum:
        - example-agent
        - container-agent
        - metrics-agent
        - '...'
        in: query
        name: type
        type: string
      - default: 1
        description: 分页编号
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        minimum: 10
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  items:
                    $ref: '#/definitions/agents.info'
                  type: array
              type: object
      summary: 获取节点列表
      tags:
      - agents
  /agents/{id}:
    get:
      operationId: /api/agents/info
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/agents.info'
              type: object
      summary: 获取某个节点信息
      tags:
      - agents
  /foo/{id}:
    get:
      operationId: /api/foo
      parameters:
      - description: 节点ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Success'
      summary: 调用example类型的agent
      tags:
      - foo
  /info/server:
    get:
      operationId: /api/info/server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/api.Success'
            - properties:
                payload:
                  $ref: '#/definitions/info.serverInfo'
              type: object
      summary: 获取当前服务器状态
      tags:
      - info
swagger: "2.0"
